-- Script para obtener todas las columnas de imHCI
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'imHCI'
ORDER BY ORDINAL_POSITION;
