-- Ver columnas de imVademecum
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'imVademecum'
ORDER BY ORDINAL_POSITION;

-- Ver columnas de VUnionModuladasNomenclador
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'VUnionModuladasNomenclador'
ORDER BY ORDINAL_POSITION;

-- Ver columnas de imInterCtrlMedicamento
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'imInterCtrlMedicamento'
ORDER BY ORDINAL_POSITION;

-- Ver columnas de imFacPracticas
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'imFacPracticas'
ORDER BY ORDINAL_POSITION;
